### ISSUE TITLE
Option to skip header row with `--csv`

### ISSUE THREAD

**Issue by luckman212** [laktak/zfind#7]
Great utility! 🙏 

I wonder if you'd consider adding a feature to skip the header row when using the `--csv` output option. As is, I have to manually parse this out using my shell which is fine, but a bit inefficient.

**Comment by laktak** [comment]
It's a great suggestion - I just implemented it, please give it a try.

**Comment by luckman212** [comment]
Works great 🚀 thank you!

One note: I could not build using `go install github.com/laktak/zfind@latest`:

```
go: github.com/laktak/zfind@latest: module github.com/laktak/zfind@latest found (v0.4.5), but does not contain package github.com/laktak/zfind
```

So I cloned the repo and built with `zfind/scripts/build`

**Comment by laktak** [comment]
Thanks for the feedback, I've fixed the readme.
